Algoritmo "Graus Cº em Fº"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antônio Calos Nicolodi
// Descrição   : Graus C em F
// Autor(a)    : Douglas Augusto Giusti
// Data atual  : 06/03/2025
Var
// Seção de Declarações das variáveis 
   f , c: real

   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite os Graus Cº ")
escreva("C: ")
leia(c)
f <- c*1.8+32
escreval ("Os Graus Fº é: ",f)

Fimalgoritmo